### ISSUE TITLE
change from ddmmyyyy to only yyyy

### ISSUE THREAD

**Issue by mverma29** [samclifford/MeganVermaMsc#10]
https://github.com/samclifford/MeganVermaMsc/blob/f44f0e50fbc2e3005851bad302c6f6651bba57fe/mscprojectscript_02_load_data.R#L153

can't figure out how to re-format this

**Comment by mverma29** [comment]
do i need to install lubridate package to do this?

**Comment by samclifford** [comment]
I'm pretty sure it is installed as part of the tidyverse package.
________________________________

**Comment by samclifford** [comment]
Other comment looks missing. Use year from lubridate.

**Comment by mverma29** [comment]
lubridate seems to only work on a singular date-time object, not a column? i used backticks and still cannot get it to work

**Comment by samclifford** [comment]
This has been fixed in 80578cc86eb7b96427416e86f9cebda336319bfa 

`lubridate::year()` is vectorised, so I'm not sure what was going wrong.

**Comment by samclifford** [comment]
We can probably stop writing stuff in the `year_issue_hh_data` branch now

**Comment by samclifford** [comment]
lubridate package has a function called year

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: mverma29 ***@***.***>
Sent: Thursday, July 28, 2022 2:25:12 PM
To: samclifford/MeganVermaMsc ***@***.***>
Cc: Samuel Clifford ***@***.***>; Assign ***@***.***>
Subject: [samclifford/MeganVermaMsc] change from ddmmyyyy to only yyyy (Issue #10)


https://github.com/samclifford/MeganVermaMsc/blob/f44f0e50fbc2e3005851bad302c6f6651bba57fe/mscprojectscript_02_load_data.R#L153<https://github.com/samclifford/MeganVermaMsc/blob/f44f0e50fbc2e3005851bad302c6f6651bba57fe/mscprojectscript_02_load_data.R#L153>

can't figure out how to re-format this
