### ISSUE TITLE
adding entries unintentionally

### ISSUE THREAD

**Issue by mverma29** [samclifford/MeganVermaMsc#11]
https://github.com/samclifford/MeganVermaMsc/blob/4eb8e29ddee23a4550dc38728b4be5d1e30b9502/mscprojectscript_02_load_data.R#L165

can't figure out why merging hh_data & respicar_socio on iso codes & years is now increasing the # of entries-- I've specified all.x (respicar_socio)

**Comment by samclifford** [comment]
Having a look at this now.

**Comment by samclifford** [comment]
You haven't done the averaging for when there's multiple data sources for the same country-year.

**Comment by samclifford** [comment]
Fixed by @mverma29 at 60a0a1aa7a64759fc4217334bee7f92d146a73f6
