### ISSUE TITLE
Getting most recent value where there's a gap in WDI/UN values

### ISSUE THREAD

**Issue by samclifford** [samclifford/MeganVermaMsc#12]
There's a lot of NA values for things like household size due to there not being annual surveys. Gimme a sec to write a function to fix this up.

**Comment by mverma29** [comment]
thank you! will the function pick the closest year to the year start of the study?

**Comment by samclifford** [comment]
Yeah I'm aiming to get the most recent non-NA value.

**Comment by samclifford** [comment]
If I do turn it into a function we should probably ensure that all the constructed data frames that are being merged in end up with the exact same names for the `iso_code` and `year` type columns.

**Comment by mverma29** [comment]
I can go back and change all of them to the exact same names

**Comment by samclifford** [comment]
Fixed in 8b2479ca5923a9aabbcd01749b5d3d74776c78c4

Function groups by country code and sorts by year, then fills down so that we get the most recent value when there's missingness and then fills up so that if there are NAs at the start of the time series we get the first one and backfill it. Make sure variables in data frame you're using it on are `iso_code` and `year`. If we have settled on a different standard, we'll just need to rename the variables inside the function
