### ISSUE TITLE
missing un subregions

### ISSUE THREAD

**Issue by mverma29** [samclifford/MeganVermaMsc#16]
https://github.com/samclifford/MeganVermaMsc/blob/fbd53b6288a8839306683fc55dc5ac2aa99dcb2b/mscprojectscript_02_load_data.R#L259

not sure why we're missing these-- could you please take a look? we have the data in the un_subregion df

**Comment by samclifford** [comment]
Which countries have missing subregions?

**Comment by samclifford** [comment]
Covered by #17

**Comment by samclifford** [comment]
Fixed in 0319043b488983c9b21687e5fbabbf82097fdde0
