### ISSUE TITLE
gini data missing for 9 countries, 23 studies

### ISSUE THREAD

**Issue by mverma29** [samclifford/MeganVermaMsc#19]
https://github.com/samclifford/MeganVermaMsc/blob/6687e48da8138638c455e38aebfd6f9fd047ecda/mscprojectscript_02_load_data.R#L221

**Comment by samclifford** [comment]
Check that id 4446 has got Sri Lanka and Saudi Arabia coded correctly as it looks like an iso3c typo. This means that while `WDI()` is getting the right info down, it isnt being merged into `respicar_socio` properly.

Philippines also seems to be coded incorrectly.

**Comment by samclifford** [comment]
Philippines also seems to be coded incorrectly

**Comment by mverma29** [comment]
It doesn't-- Sri Lanka, Saudi Arabia and the Philippines are all coded incorrectly
Sri Lanka: 144
Saudi Arabia: 682
The Philippines: 608

https://www.iban.com/country-codes

**Comment by samclifford** [comment]
I'll fix that in the source data and upload a new version

**Comment by mverma29** [comment]
thanks-- do we just think that was an issue for study 4446 or should I double-check all 73 ISO codes? I checked for all the other covariates with missingness, they're all just missing, ISO's are fine

**Comment by samclifford** [comment]
It'll just be 4446 that's the issue. It's been a perpetual thorn in my side because I'm not sure the data was collated correctly the first time around.

**Comment by mverma29** [comment]
that's a relief. time to try out gitblame?

**Comment by samclifford** [comment]
This would have been at data entry

**Comment by mverma29** [comment]
ISO code for Sri Lanka is still wrong, re-downloaded data today

**Comment by samclifford** [comment]
I have now uploaded a new version to Dropbox after rebuilding the 4446 entries

**Comment by samclifford** [comment]
Just checked and I only have Saudi Arabia and Cuba missing now for Gini. Everything's accounted for GDP and urban percent.

**Comment by samclifford** [comment]
Saudia Arabia estimates included as of e2192a9b2cfc414d01a0d6a60e7356c2a87425a9

**Comment by samclifford** [comment]
Cuba included as of 70b969a4798b191398853d0f3838a6248c1749f2
