### ISSUE TITLE
Tidying up mscprojectscript_02_load_data.R

### ISSUE THREAD

**Issue by samclifford** [samclifford/MeganVermaMsc#20]
There's a lot of diagnostic stuff in the script that is commented out, but the main issue is that there's now a bunch of extra stuff for building the additional data that I've sourced as well as that we import all variables and then clean and merge all those variables.

We might be better off either making separate scripts to handle each variable or even just reorganising it so that each variable is dealt with one at a time. At the very least we may want to write a function that does the merging so that it isn't being copy-pasted multiple times.

**Comment by mverma29** [comment]
split into 6 scripts for each variable, still need to write a function for the merging
