### ISSUE TITLE
Missing female education variable

### ISSUE THREAD

**Issue by samclifford** [samclifford/MeganVermaMsc#21]
The following countries have no female education values listed for these years

| ISO 3166-1|Country       |  Min|  Max|  n|
|----------:|:-------------|----:|----:|--:|
|        158|Taiwan        | 1998| 2007|  7|
|        540|New Caledonia | 2002| 2002|  1|

**Comment by mverma29** [comment]
still not working-- I see lines 127-134 were supposed to fix the Taiwan data but that hasn't worked, for some reason

**Comment by samclifford** [comment]
I had to move the TWN data down to where the `female_ed` gets merged with `respicar_socio`. Fixed in ac8d11518c3884913cc5129f043069c594b45d82

**Comment by samclifford** [comment]
I've closed it without being able to fix the New Caledonia `female_ed` value because [estimates](https://www.nationsencyclopedia.com/WorldStats/Edu-secondary-enrollment-rate-female.html) and calculations I do based on scraping partial info from WDI and national data indicates that there are more girls in high school in NCL than there are girls aged 15-19. We might have to omit NCL from the analysis.
