### ISSUE TITLE
Data exploration 

### ISSUE THREAD

**Issue by mverma29** [samclifford/MeganVermaMsc#24]
exploratory analysis (scatterplots) for carriage v. : 

- [x] urban percent 
- [x] gdp
- [ ] gdp by UN subregion? 
- [x] gini
- [x] household size 
- [x] female education 
- [x] un subregion

**Comment by mverma29** [comment]
try coloring scatterplot of gdp by UN subregion, then...
facetwrap each gdp subregion plot, grey points for all, color by subregion (15)


or
make a pairs plot, change the point colors in gdp and gini scatterplots to subregion?? might be a mess

**Comment by samclifford** [comment]
I'd make the scatterplot points even lighter. Another option is to `mutate`, rather than de`select`, the `subregion` variable for the second `geom_point()` so that it has the value "World" and can appear at the end of a 4x4 grid.

**Comment by mverma29** [comment]
I like the background scatterplot points so i chose the first option in [32a0489](https://github.com/samclifford/MeganVermaMsc/commit/32a0489c23cf41e06aef399790c982adcfd8f4df)
