### ISSUE TITLE
Sensitivity analyses

### ISSUE THREAD

**Issue by mverma29** [samclifford/MeganVermaMsc#27]
- [x] full model (with interaction & without?) with datasets excluding ethnic minority
- [x] full model (with interaction & without?) with cross-sectional datasets only? 
- [x] split by age group?

**Comment by samclifford** [comment]
- [ ] restriction to only those with staleness of 0 for all covariates 

This may be a small data set

**Comment by samclifford** [comment]
Are you still planning on doing these?

**Comment by mverma29** [comment]
yes, but after i do all the writing for the basic stuff

**Comment by mverma29** [comment]
> * [ ]  restriction to only those with staleness of 0 for all covariates
> 
> This may be a small data set

this was only 3 studies so will not be including this any more

**Comment by mverma29** [comment]
done in script 6: sensitivity analyses
