### ISSUE TITLE
Subregions don't match

### ISSUE THREAD

**Issue by samclifford** [samclifford/MeganVermaMsc#34]
https://github.com/samclifford/MeganVermaMsc/blob/6e98e78cb50fad0a9a3b493f87f7845eec2c95f8/mscprojectscript_03_explore_data.R#L104

The world map `subregion` field doesn't look like it's the UN subregion variable. You may need to calculate the UN subregion based on the iso code in the world map. Currently the following are in `respicar_socio` but not `subworld`

```
Latin America and the Caribbean
South-eastern Asia             
Sub-Saharan Africa    
```

**Comment by mverma29** [comment]
oh no! how would i find the geometries of the subregions by iso code? that's why i had merged it with the world dataset

**Comment by mverma29** [comment]
fixed using countrycode

**Comment by samclifford** [comment]
The summarise we do on the world map is what generates the geometry for the subregions.

**Comment by samclifford** [comment]
> fixed using countrycode

Have you pushed this?
