### ISSUE TITLE
weighting for total population not working 

### ISSUE THREAD

**Issue by mverma29** [samclifford/MeganVermaMsc#35]
https://github.com/samclifford/MeganVermaMsc/blob/961392a620a30cc25e10c49449190025edc4db61/mscprojectscript_03_explore_data.R#L95-L99

error says x and w are not of the same length, and the issue occurs in Australia and New Zealand

**Comment by samclifford** [comment]
Backticks around 2020, as its a column name that is a number. At the moment it thinks you mean the actual number 2020.

**Comment by samclifford** [comment]
It's failing on Australia and New Zealand because it is first alphabetically
