### ISSUE TITLE
add subregion border 

### ISSUE THREAD

**Issue by mverma29** [samclifford/MeganVermaMsc#36]
https://github.com/samclifford/MeganVermaMsc/blob/e952f4821dd298a2fa3e4074604e2f118dd028d3/mscprojectscript_03_explore_data.R#L135-L143

i've tried borders, geom_polygon & geom_sf and still haven't figured it out -- please help!

**Comment by mverma29** [comment]
use geom_sf to add a layer of boundaries

**Comment by mverma29** [comment]
[2d4b1b0](https://github.com/samclifford/MeganVermaMsc/commit/2d4b1b003b31925549536ce1e2c31d755bbe2341)

didn't work-- any suggestions? the UN geoscheme map data from UN doesn't have geometries attached

**Comment by samclifford** [comment]
Fixed in 1d9cd36cf08ec3db38b7ba52baf79a86a65483b8
