### ISSUE TITLE
Obtaining p from cases per million.

### ISSUE THREAD

**Issue by samclifford** [samclifford/MeganVermaMsc#4]
https://github.com/samclifford/MeganVermaMsc/blob/df07e267b4fff8c36ffa0f49e96c9599066b9973/task_glm.Rmd#L387

If we had 500,000 cases per 1,000,000 people that's a prevalence of 0.5 (500,000/1,000,000). As discussed in person the other day we don't strictly have 'number of people who have had COVID', but in terms of comparing to the RESPICAR data this is the approach that makes sense.

**Comment by mverma29** [comment]
That makes sense, for some reason I thought total cases per million would already  be the prevalence (a proportion) but obviously that's not what the dataset includes.
