### ISSUE TITLE
Change approach for mixed effects model

### ISSUE THREAD

**Issue by samclifford** [samclifford/MeganVermaMsc#40]
This should close #38 and #39

The buildmer package has a function called `buildgamm4()` which allows us to use the gamm4 package's approach to building mixed effects models. Rather than passing in a `random` argument, we add the grouping structure to the end of the `formula`, e.g. `y ~ x + (1|z)` and then everything else is the same as the specification in `glm()`-type models.

The broom.mixed package has a `tidy` method for the fitted model. You just have to call it on the `model` attribute, e.g. if we do `mymod <- buildgamm4(...)` then we use `tidy(mymod@model)`. Then it's a matter of calculating confidence intervals from there, exponentiating to convert to odds ratios and interpreting the results.

**Comment by samclifford** [comment]
Also we no longer need to scale by 100 to convert percentages to proportions. This will make it easier to interpret the odds ratios.

**Comment by mverma29** [comment]
used gamm4 & buildgamm4 for all models with RE term
