### ISSUE TITLE
broken function for filtering each covariate's staleness 

### ISSUE THREAD

**Issue by mverma29** [samclifford/MeganVermaMsc#41]
https://github.com/samclifford/MeganVermaMsc/blob/bc5c9a81f33b7f41e85c68237e08452c65daa1fa/mscprojectscript_01_load_packages.R#L134-L138

do you see anything obviously wrong here? i can't figure it out

**Comment by samclifford** [comment]
Line 136 should have a pipe at the end of it. Also why make a different object for each variable when you can apply this to the whole data frame? And why five years?

**Comment by mverma29** [comment]
thank you! I was just thinking for write-up purposes I might want to mention the total studies with 5 or more years of staleness, though that's kind of arbitrary

**Comment by mverma29** [comment]
still not working after fixing the pipe

**Comment by samclifford** [comment]
https://github.com/samclifford/MeganVermaMsc/blob/7532afdf275d0c3acd31cbed2d31b9e9b6b68b37/mscprojectscript_01_load_packages.R#L136

There's no rows in the data frame where `variable` has the value `"x"` and so it's returnin a data frame with zero rows.

**Comment by mverma29** [comment]
right, but i'm still not sure why (i'm testing out with the gini variable, as there should be 56 entries, instead of the urban_percent, which has 0 stale values)

**Comment by samclifford** [comment]
With the state of the code as of 7532afdf275d0c3acd31cbed2d31b9e9b6b68b37 there is no line where the variable `x` gets used. On line 136, `filter(variable == "x")` says "match the following condition: find where the column `variable` has the value of the string of text `"x"`". As opposed to where the column `variable` has the same value as what was passed in to the function as `x`.

**Comment by mverma29** [comment]
oh i understand the issue now, thank you! how does one refer back to what was passed into the function as x? 

i tried changing it to filter(variable == x) but it gives me an error: 
Error in `filter()`:
! Problem while computing `..1 = variable == x`.
✖ Input `..1` must be of size 2190 or 1, not size 9312.
Backtrace:
 1. global covariate_staleness_socio(gini)
 5. dplyr:::filter.data.frame(., variable == x)

**Comment by samclifford** [comment]
You could rewrite the function to take in a data frame (rather than calling `respicar_socio` from within) as its first argument and have the second argument be the variable name(s) you want as a vector of strings (changing `==` to be `%in%`).

Or alternatively you could do all the staleness thing in one step by grouping the `staleness_socio` data frame by `variable` and then summarising to get the mean number of rows where staleness meets that condition, or the mean staleness, etc.

**Comment by samclifford** [comment]
> oh i understand the issue now, thank you! how does one refer back to what was passed into the function as x?

Replace `"x"` with `x`.

**Comment by mverma29** [comment]
saw your push, but still have the same error I was getting here:

> oh i understand the issue now, thank you! how does one refer back to what was passed into the function as x?
> 
> i tried changing it to filter(variable == x) but it gives me an error: Error in `filter()`: ! Problem while computing `..1 = variable == x`. ✖ Input `..1` must be of size 2190 or 1, not size 9312. Backtrace:
> 
> 1. global covariate_staleness_socio(gini)
> 2. dplyr:::filter.data.frame(., variable == x)

**Comment by samclifford** [comment]
Are you passing the variable name in quote marks?

**Comment by mverma29** [comment]
no, tried that and it fixed it. thank you!
