### ISSUE TITLE
gamm4 without RE not possible?

### ISSUE THREAD

**Issue by mverma29** [samclifford/MeganVermaMsc#42]
https://github.com/samclifford/MeganVermaMsc/blob/6259206075c07c9c4cfbeb38e006e0cc0cd8bf1d/mscprojectscript_05_multivariate_models.R#L4-L7

can only use gamm4 to with “at least 1 smooth or at least one other random effect” so can’t do full model without RE to do LRT to show that RE are valid

**Comment by samclifford** [comment]
Fit this as a GLM. You may have to do the LRT 'by hand' by pulling out the deviance from each of the two models, finding their difference, finding the difference in degrees of freedom used by each model, then looking in the tail of the <i>&chi;</i><sup>2</sup> distribution.

**Comment by mverma29** [comment]
[c77764b](https://github.com/samclifford/MeganVermaMsc/commit/c77764b123c2ecc5d9967f132bd83dbd217ab741)

having issues fitting full stepwise model -- not allowing random effects term
