### ISSUE TITLE
unable to add AIC to model summary tables

### ISSUE THREAD

**Issue by mverma29** [samclifford/MeganVermaMsc#43]
https://github.com/samclifford/MeganVermaMsc/blob/86ecc792466a218311957b130623cc9d75aa63ca/mscprojectscript_05_multivariate_models.R#L95

This should work but I keep getting an error

**Comment by samclifford** [comment]
What's the error, as this works fine for me.

**Comment by mverma29** [comment]
Making the table works fine, but when i try to save it after adding the add_glance_source (lines 97-99) it gives me this error:

Usage of empty symbol '' with footnote should not happen, use `add_footer_lines()` instead, it does not require any symbol. This usage will be forbidden in the next release. Please, wait for 10 seconds!

and add_footer_lines() doesn't seem to work either

**Comment by samclifford** [comment]
Will have another look.

**Comment by samclifford** [comment]
I also see this message when using the code to add the glance note and write to docx but I think it's a warning rather than an error as it still writes the table to file.

**Comment by mverma29** [comment]
the table it writes still doesn't have the AIC (at least on my end)
