### ISSUE TITLE
Output tables

### ISSUE THREAD

**Issue by samclifford** [samclifford/MeganVermaMsc#44]
https://github.com/samclifford/MeganVermaMsc/blob/86ecc792466a218311957b130623cc9d75aa63ca/mscprojectscript_04_univariate_models.R#L43

Make sure that you're using relative paths (e.g. `outputs/urban_percent_re.docx`) rather than absolutes (e.g. `/Users/meganverma/Desktop/git/MeganVermaMsc/outputs/urban_percent_re.docx`)

**Comment by samclifford** [comment]
Are you manually removing the intercept rows and relabelling the Characteristic column with a human-friendly label?

**Comment by samclifford** [comment]
Oh you can set `intercept = FALSE` inside `tbl_regression()`!

**Comment by mverma29** [comment]
the default is intercept=FALSE but even when i specify it, it's still in my tables, so planning on manually removing. I spent quite some time trying to relabel the respicar_socio covariates but R pulls the variable name, not the variable label for the model output (both summary and tidy, I believe) so it makes sense to just manually relabel

**Comment by samclifford** [comment]
One option would be writing a function to replace the standard tidier used, as I suspect the mixed effects model is to blame. You could filter out anything matching Intercept, remove leading X and then make a table of human friendly names to merge in. But that might be for another day.

**Comment by mverma29** [comment]
Yeah after spending a few hours on it, i realized it would take me much less time to just manually change the tables. The annoying part is filling in the values anyway, and that's done already. Will figure this out post-Msc!
