### ISSUE TITLE
Interpretability of ORs for female education, urban percent and gini coefficient

### ISSUE THREAD

**Issue by samclifford** [samclifford/MeganVermaMsc#45]
Just been looking at the output tables from the fitted multivariate models. To two decimal places the CIs appear equivalent and when you've got an estimate of 1.00 with a 95% CI of (1.00, 1.00) it's not immediately clear whether this is an increase or decrease.

It may be worth looking at scaling these variables to be tenths rather than hundreths (so divide these values by ten, putting them in the 0-10ish range (acknowledging that female education can be greater than 100%)) so that the ORs are for a ten percent change in the variable, rather than a one percent change.

**Comment by mverma29** [comment]
fixed in [70e6fb4](https://github.com/samclifford/MeganVermaMsc/commit/70e6fb403edd7ce6b575f7a6ec37c952bead987b)

**Comment by samclifford** [comment]
Make sure that you adequately discuss in the model fitting section of the report that you fit with a 10 percent change, but have any exploratory plots still using the 1 percent version of the variables (this may mean making a new column which is 0.1*x for each variable rather than overwriting).

**Comment by mverma29** [comment]
fixed here 
[af31312](https://github.com/samclifford/MeganVermaMsc/commit/af313121bd6df1684a4200b556e28107b1930bcb)
