### ISSUE TITLE
group_by & summarize not working, again

### ISSUE THREAD

**Issue by mverma29** [samclifford/MeganVermaMsc#46]
https://github.com/samclifford/MeganVermaMsc/blob/829841db1a1e697a1fe9e58cd42e02dbca7fd9d1/mscprojectscript_03.3_descriptive_stats_covariate.R#L195-L198

i cant remember why this failed last time but it's not working yet again

**Comment by samclifford** [comment]
You need to sum Total within summarise.

**Comment by mverma29** [comment]
fixed in [5730bb4](https://github.com/samclifford/MeganVermaMsc/commit/5730bb402768cdf601385ad2672576c16eb54d13)
