### ISSUE TITLE
Correlation matrices

### ISSUE THREAD

**Issue by samclifford** [samclifford/MeganVermaMsc#47]
https://github.com/samclifford/MeganVermaMsc/blob/149b9cf78c00a51b4c9781165d5ac16273141269/mscprojectscript_03.3_descriptive_stats_covariate.R#L231

I'd probably go with using pairwise complete given the amount of missingness in some of these variables.

**Comment by mverma29** [comment]
happy to change it but when i looked up pairwise comparison this article came up with a very strong opinion lol
https://bwlewis.github.io/covar/missing.html

**Comment by mverma29** [comment]
actually i read a stackexchange page and i agree that's the best route--- i didn't realize the whole columns were getting dropped when using complete.obs-- fixed in 712bba052289702fec2bce260e03fd3cca7e66d5
