### ISSUE TITLE
Data on Dropbox

### ISSUE THREAD

**Issue by samclifford** [samclifford/MeganVermaMsc#7]
Data available now on private Dropbox folder.

- [x] Copy to local folder
- [x] Add to `.gitignore` file
- [x] Alert @samclifford as to where the file is located and what its name is so that we aren't using something like `read_csv("Absolute_path_to_folder_only_Megan_has/data.csv")

**Comment by mverma29** [comment]
@ samclifford the file is in the data folder in the MeganVermaMsc repo :)

**Comment by samclifford** [comment]
Thanks
