### ISSUE TITLE
carriage is over 100% in 3 studies

### ISSUE THREAD

**Issue by mverma29** [samclifford/MeganVermaMsc#9]
https://github.com/samclifford/MeganVermaMsc/blob/1bf8d0ec13a73036616e202c04dab243a82550ef/mscprojectscript_03_explore_data.R#L28

@samclifford please look into RESPICAR dataset when you have a chance

**Comment by samclifford** [comment]
> id 19645, with 921 positive and 130 total and 19324 21422 with almost the same number positive as the total

**Comment by samclifford** [comment]
I'll make changes to the cleaner code from RESPICAR to add this but basically

| ID | DOI | Total | Positive | Notes | 
| --:| :-- | --: | --: | :-- |
| 19645 | https://doi.org/10.1086/431679 | 126 | 101 | At time of enrolment | 
| 19645 | https://doi.org/10.1086/431679 | 126 | 121 | 1 year follow-up | 
| 19645 | https://doi.org/10.1086/431679 | 115 | 62 | 2 years follow-up | 
| 19324 | https://doi.org/10.1128/jcm.01551-07 | 414 | 254 | Seems columns were shifted |
| 21422 | https://doi.org/10.1371/journal.pone.0166018 | 1723 | 957 | Total number of samples and individuals reversed |

**Comment by samclifford** [comment]
Values have been updated and new data is in Dropbox
